server:
  port: 9081

spring:
  application:
    name: keycloak-adapter-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

  client-id: bodgen-microservice
  client-secret: 123
  scope: profile
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token

logging:
  level:
    root: INFO